set(_CATKIN_CURRENT_PACKAGE "myrobot")
set(myrobot_VERSION "0.0.0")
set(myrobot_MAINTAINER "myrobot <myrobot@todo.todo>")
set(myrobot_PACKAGE_FORMAT "2")
set(myrobot_BUILD_DEPENDS )
set(myrobot_BUILD_EXPORT_DEPENDS )
set(myrobot_BUILDTOOL_DEPENDS "catkin")
set(myrobot_BUILDTOOL_EXPORT_DEPENDS )
set(myrobot_EXEC_DEPENDS )
set(myrobot_RUN_DEPENDS )
set(myrobot_TEST_DEPENDS )
set(myrobot_DOC_DEPENDS )
set(myrobot_URL_WEBSITE "")
set(myrobot_URL_BUGTRACKER "")
set(myrobot_URL_REPOSITORY "")
set(myrobot_DEPRECATED "")